version: '3.9'
services:
  web: # 1st Container: for hosting our development server
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests: # 2nd Container: for running tests/re-runrning tests in case "any" file changes
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]